- name: setenforce 
  ansible.builtin.command: setenforce 0

- name: Start Service
  ansible.builtin.systemd_service:
    name: firewalld
    state: stopped


- name: Run Python
  ansible.builtin.include_role:
    name: common
    tasks_from: python

- name: Run systemd_setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup