- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Start MySQL
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: yes

#- name: Setup MySQL Root Password
#  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/{{ app_name }}:password token={{ token }} url=http://vault-int.vidyapractice.online:8200') }}

- name: Setup MySQL Root Password
  ansible.builtin.shell: >
    mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY
    '{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' + env + '/data/' + app_name + ':password token=' + token + ' url=http://vault-int.vidyapractice.online:8200') }}';"
  no_log: true


#   - name: Install MySQL Server
#   ansible.builtin.dnf:
#     name: mariadb-server
#     state: latest

# - name: Start MySQL
#   ansible.builtin.systemd_service:
#     name: mariadb
#     state: started
#     enabled: yes

# - name: Setup MySQL Root Password
#   ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/{{ app_name }}:password token={{ token }} url=http://vault-int.vidyapractice.online:8200') }}